# Aplicacion
spring.application.name=autoridades-service
server.port=8082

# Base de Datos


# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Logs
logging.level.com.proyecto.autoridadesservice=DEBUG

#EurekaClient

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true